"""create career recommendations table

Revision ID: 544288c28046
Revises: 3823e6457d97
Create Date: 2026-08-10 19:19:58.403442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544288c28046'
down_revision: Union[str, Sequence[str], None] = '3823e6457d97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_target_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=30), server_default='medium', nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_target_id'], ['career_targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_recommendations_career_target_id'), 'career_recommendations', ['career_target_id'], unique=False)
    op.create_index(op.f('ix_career_recommendations_id'), 'career_recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_career_recommendations_user_id'), 'career_recommendations', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_recommendations_user_id'), table_name='career_recommendations')
    op.drop_index(op.f('ix_career_recommendations_id'), table_name='career_recommendations')
    op.drop_index(op.f('ix_career_recommendations_career_target_id'), table_name='career_recommendations')
    op.drop_table('career_recommendations')
    # ### end Alembic commands ###
