"""create skill gaps table

Revision ID: 666a662717db
Revises: 619e7edf06a8
Create Date: 2026-08-09 19:37:10.140421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666a662717db'
down_revision: Union[str, Sequence[str], None] = '619e7edf06a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill_gaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_target_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='missing', nullable=False),
    sa.Column('importance', sa.String(length=30), server_default='medium', nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_target_id'], ['career_targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_gaps_career_target_id'), 'skill_gaps', ['career_target_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_id'), 'skill_gaps', ['id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_skill_id'), 'skill_gaps', ['skill_id'], unique=False)
    op.create_index(op.f('ix_skill_gaps_user_id'), 'skill_gaps', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_gaps_user_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_skill_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_id'), table_name='skill_gaps')
    op.drop_index(op.f('ix_skill_gaps_career_target_id'), table_name='skill_gaps')
    op.drop_table('skill_gaps')
    # ### end Alembic commands ###
