"""create career_targets table

Revision ID: 832a4d617eb1
Revises: 6c2707ee9b98
Create Date: 2026-08-09 19:17:21.050120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '832a4d617eb1'
down_revision: Union[str, Sequence[str], None] = '6c2707ee9b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('target_role', sa.String(length=100), nullable=False),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_targets_id'), 'career_targets', ['id'], unique=False)
    op.create_index(op.f('ix_career_targets_user_id'), 'career_targets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_targets_user_id'), table_name='career_targets')
    op.drop_index(op.f('ix_career_targets_id'), table_name='career_targets')
    op.drop_table('career_targets')
    # ### end Alembic commands ###
