"""create job matches table

Revision ID: 8c869ac03f7a
Revises: 666a662717db
Create Date: 2026-08-09 19:38:42.192170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c869ac03f7a'
down_revision: Union[str, Sequence[str], None] = '666a662717db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('career_target_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=150), nullable=False),
    sa.Column('job_title', sa.String(length=150), nullable=False),
    sa.Column('job_description', sa.Text(), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_skills', sa.Text(), nullable=True),
    sa.Column('missing_skills', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_target_id'], ['career_targets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_career_target_id'), 'job_matches', ['career_target_id'], unique=False)
    op.create_index(op.f('ix_job_matches_id'), 'job_matches', ['id'], unique=False)
    op.create_index(op.f('ix_job_matches_user_id'), 'job_matches', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_job_matches_user_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_id'), table_name='job_matches')
    op.drop_index(op.f('ix_job_matches_career_target_id'), table_name='job_matches')
    op.drop_table('job_matches')
    # ### end Alembic commands ###
