"""add skill gaps to job matches

Revision ID: a3ef4ba7a39e
Revises: e4b09e8743bd
Create Date: 2026-08-14 19:29:37.320299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3ef4ba7a39e'
down_revision: Union[str, Sequence[str], None] = 'e4b09e8743bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_matches', sa.Column('skill_gaps', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_matches', 'skill_gaps')
    # ### end Alembic commands ###
