"""add per user ai usage tracking

Revision ID: a6dee22a7962
Revises: bdda9eee7321
Create Date: 2026-08-12 10:18:08.179366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6dee22a7962'
down_revision: Union[str, Sequence[str], None] = 'bdda9eee7321'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_ai_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('total_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'usage_date', name='uq_user_ai_usage_user_date')
    )
    op.create_index(op.f('ix_user_ai_usage_id'), 'user_ai_usage', ['id'], unique=False)
    op.create_index(op.f('ix_user_ai_usage_usage_date'), 'user_ai_usage', ['usage_date'], unique=False)
    op.create_index(op.f('ix_user_ai_usage_user_id'), 'user_ai_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_ai_usage_user_id'), table_name='user_ai_usage')
    op.drop_index(op.f('ix_user_ai_usage_usage_date'), table_name='user_ai_usage')
    op.drop_index(op.f('ix_user_ai_usage_id'), table_name='user_ai_usage')
    op.drop_table('user_ai_usage')
    # ### end Alembic commands ###
