"""create internship applications table

Revision ID: fe7dc8d7e543
Revises: 8ea70ec517c1
Create Date: 2026-07-18 16:35:53.291454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe7dc8d7e543'
down_revision: Union[str, Sequence[str], None] = '8ea70ec517c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('internship_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('job_url', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('applied_date', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internship_applications_id'), 'internship_applications', ['id'], unique=False)
    op.create_index(op.f('ix_internship_applications_user_id'), 'internship_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_internship_applications_user_id'), table_name='internship_applications')
    op.drop_index(op.f('ix_internship_applications_id'), table_name='internship_applications')
    op.drop_table('internship_applications')
    # ### end Alembic commands ###
