"""create career target skills table

Revision ID: 05e490e337ea
Revises: 8c869ac03f7a
Create Date: 2026-08-10 19:16:26.028946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05e490e337ea'
down_revision: Union[str, Sequence[str], None] = '8c869ac03f7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_target_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_target_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('importance', sa.String(length=30), server_default='required', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['career_target_id'], ['career_targets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_target_skills_career_target_id'), 'career_target_skills', ['career_target_id'], unique=False)
    op.create_index(op.f('ix_career_target_skills_id'), 'career_target_skills', ['id'], unique=False)
    op.create_index(op.f('ix_career_target_skills_skill_id'), 'career_target_skills', ['skill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_career_target_skills_skill_id'), table_name='career_target_skills')
    op.drop_index(op.f('ix_career_target_skills_id'), table_name='career_target_skills')
    op.drop_index(op.f('ix_career_target_skills_career_target_id'), table_name='career_target_skills')
    op.drop_table('career_target_skills')
    # ### end Alembic commands ###
