"""link skill gaps to goals

Revision ID: 3823e6457d97
Revises: 05e490e337ea
Create Date: 2026-08-10 19:17:17.529230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3823e6457d97'
down_revision: Union[str, Sequence[str], None] = '05e490e337ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gaps', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_skill_gaps_goal_id'), 'skill_gaps', ['goal_id'], unique=False)
    op.create_foreign_key(None, 'skill_gaps', 'goals', ['goal_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill_gaps', type_='foreignkey')
    op.drop_index(op.f('ix_skill_gaps_goal_id'), table_name='skill_gaps')
    op.drop_column('skill_gaps', 'goal_id')
    # ### end Alembic commands ###
