"""add user skill levels

Revision ID: b7918eadab6c
Revises: a3ef4ba7a39e
Create Date: 2026-08-24 18:42:30.180751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7918eadab6c'
down_revision: Union[str, Sequence[str], None] = 'a3ef4ba7a39e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_skills', sa.Column('level', sa.String(length=30), server_default='beginner', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_skills', 'level')
    # ### end Alembic commands ###
