"""add unique constraint to user skills

Revision ID: ba7c2cab4f07
Revises: c4d8e2f1a9b7
Create Date: 2026-09-04 17:18:33.863832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba7c2cab4f07'
down_revision: Union[str, Sequence[str], None] = 'c4d8e2f1a9b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_skills_user_skill', 'user_skills', ['user_id', 'skill_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_skills_user_skill', 'user_skills', type_='unique')
    # ### end Alembic commands ###
